name: CI/CD Webdriverio

on:
  push:
    branches:
      - main 
  workflow_dispatch:   
  schedule:
    - cron: '0 12 24 6 *'  


jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Install dependencies
        run: npm install

      - name: Run Main WebdriverIO Test only
        run: npx wdio run ./wdio.conf.js --spec eCommerceE2E.js

      - name: Commit & Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "CI/CD: Auto-push full project" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:main
